[[headers]]
  for = "/*.html"
    [headers.values]
    Cache-Control = "max-age=3600"

[[headers]]
  for = "/static/css/*"
    [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

